### ISSUE TITLE
java.util.ConcurrentModificationException in ConnectionManager

### ISSUE THREAD

**Issue by kpvdr** [kpvdr/amqp-build-trigger#12]
An occurrence of `java.util.ConcurrentModificationException` has been observed in `ConnectionManager`. This occurs where a `HashMap` iterator is calling `next()` (see trace below). 

Manual inspection of the code also turned up a place where an `ArrayList` instance may also be used in a multithreaded environment in `AmqpBuildTrigger`.

This error can be triggered by changing or deleting a trigger while a job previously triggered by the trigger is still in progress.

Output:
```
Timer task com.redhat.jenkins.plugins.amqpbuildtrigger.ConnectionUpdateTimer@65f692ac failed
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
	at com.redhat.jenkins.plugins.amqpbuildtrigger.ConnectionManager.update(ConnectionManager.java:92)
	at com.redhat.jenkins.plugins.amqpbuildtrigger.ConnectionUpdateTimer.doAperiodicRun(ConnectionUpdateTimer.java:42)
	at hudson.model.AperiodicWork.doRun(AperiodicWork.java:88)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kpvdr** [comment]
I have changed the instance of `java.util.HashMap` in the above trace for `java.util.concurrent.ConcurrentHashMap`, which appears to be the recommended approach to solve this.

In addition, I changed the `java.util.ArrayList` for `java.util.concurrent.CopyOnWriteArrayList` as a precaution.

Testing by removing and/or changing a trigger's parameters while a job triggered by it is still running shows no problems. I will close this in a few weeks if no other reports of errors show up.
